services:

  dns:
    image: dns:latest
    build:
      context: .
      dockerfile: dns/Dockerfile
    container_name: dns
    restart: unless-stopped
    ports:
      - 28080:8080
    environment:
      - DNS_ADDRESS=:8080
      - PATH=/etc/resolv.conf
      - GRACEFULSHUTDOWN=2
